### ISSUE TITLE
Failed to upgrade

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/roundcube_ynh#17]
Maxime said he had a error when he tried to upgrade rouncube.

https://pastebin.com/qRqk173R
Something around the line 160.

**Comment by alexAubin** [comment]
This looks like at least $final_path was not set properly :/

**Comment by maniackcrudelis** [comment]
Probably !
There's no section for fixes old things in this upgrade script.
And during the refactoring, we're not able to test the upgrade, because the previous version doesn't works.

But... That means also nobody try to upgrade during the testing release...

So, I can't go to bed now, there's the first Blade runner on Arte just now !!!
I'm going to fix that.

**Comment by maniackcrudelis** [comment]
Should be fixed by this PR https://github.com/YunoHost-Apps/roundcube_ynh/pull/18

**Comment by Gwend4l** [comment]
Unfortunately, I still cannot upgrade despite the PR :(

Here are my logs: https://framabin.org/?e9dd5b2ec4fe6486#Ey5+M/bWXWswIW6FAH2kTch0SiLXUdn98Ku5Da7pCyA=

So something in there I suppose:
```
++ grep RCMAIL_VERSION /program/include/iniset.php
++ cut '-d'\''' -f4
Warning: grep: /program/include/iniset.php: No such file or directory
+ oldversion=
+ ynh_app_setting_set roundcube final_path
Warning: /usr/share/yunohost/helpers.d/setting: line 17: $3: unbound variable
++ ynh_exit_properly
++ exit_code=1
Warning: !!
++ '[' 1 -eq 0 ']'
++ trap '' EXIT
Warning:   roundcube's script has encountered an error. Its execution was cancelled.
++ set +eu
++ echo -e '!!\n  roundcube'\''s script has encountered an error. Its execution was cancelled.\n!!'
```

**Comment by mokas01** [comment]
in my case, the upgrade (failed and) after 2 attempts made the app "disappear". If i then try

> yunohost app upgrade roundcube -u https://github.com/YunoHost-Apps/roundcube_ynh

but it failed : 

> roundcube n'est pas installé

**Comment by JimboJoe** [comment]
Fixed by https://github.com/YunoHost-Apps/roundcube_ynh/commit/7a82a242819d40c283364c4c18c5d18c8e78c5fb

**Comment by Gwend4l** [comment]
Thanks for the upgrade! Unfortunately there is yet another problem with my upgrade, it seems.
Here are the logs: https://framabin.org/?d2d2fca163dcbeed#Fx/IVpgL1TX8PUeXfKkcqF3KIy4aGiMBt1GUNpMpbVg=

So something around here:
```
+ cd /var/www/roundcube 
+ /usr/bin/php -q ./bin/installto.sh /var/www/roundcube 
Warning: Error 500: Installation at target location is up-to-date! 
Warning: !! 
+ ynh_exit_properly 
Warning: roundcube's script has encountered an error. Its execution was cancelled.
```

Should I open a new issue?
